import { ReactElement } from "react";

import Angular from "../icons/angular.svg?react";
import Bell from "../icons/bell.svg?react";
import Chart from "../icons/chart.svg?react";
import Docker from "../icons/docker.svg?react";
import Email from "../icons/email.svg?react";
import File from "../icons/file.svg?react";
import Firebase from "../icons/firebase.svg?react";
import Github from "../icons/github.svg?react";
import Gitlab from "../icons/gitlab.svg?react";
import Kotlin from "../icons/kotlin.svg?react";
import Location from "../icons/location.svg?react";
import Mobx from "../icons/mobx.svg?react";
import Mui from "../icons/mui.svg?react";
import Nextui from "../icons/nextUi.svg?react";
import Nginx from "../icons/nginx.svg?react";
import Pnpm from "../icons/pnpm.svg?react";
import React from "../icons/react.svg?react";
import Reactquery from "../icons/reactQuery.svg?react";
import Redux from "../icons/redux.svg?react";
import Reporting from "../icons/reporting.svg?react";
import Socket from "../icons/socket.svg?react";
import Tailwind from "../icons/tailwind.svg?react";
import Telegram from "../icons/telegram.svg?react";
import Ts from "../icons/ts.svg?react";
import Vite from "../icons/vite.svg?react";

// Autogenerated by script - do not edit manually

export type IconType =
    | "angular"
    | "bell"
    | "chart"
    | "docker"
    | "email"
    | "file"
    | "firebase"
    | "github"
    | "gitlab"
    | "kotlin"
    | "location"
    | "mobx"
    | "mui"
    | "nextui"
    | "nginx"
    | "pnpm"
    | "react"
    | "reactquery"
    | "redux"
    | "reporting"
    | "socket"
    | "tailwind"
    | "telegram"
    | "ts"
    | "vite"

export type IconProps = React.SVGProps<SVGSVGElement>;

export const IconMap: Record<IconType, (props: IconProps) => ReactElement> = {
  ["angular"]: ({ ...props }) => <Angular {...props} />,
  ["bell"]: ({ ...props }) => <Bell {...props} />,
  ["chart"]: ({ ...props }) => <Chart {...props} />,
  ["docker"]: ({ ...props }) => <Docker {...props} />,
  ["email"]: ({ ...props }) => <Email {...props} />,
  ["file"]: ({ ...props }) => <File {...props} />,
  ["firebase"]: ({ ...props }) => <Firebase {...props} />,
  ["github"]: ({ ...props }) => <Github {...props} />,
  ["gitlab"]: ({ ...props }) => <Gitlab {...props} />,
  ["kotlin"]: ({ ...props }) => <Kotlin {...props} />,
  ["location"]: ({ ...props }) => <Location {...props} />,
  ["mobx"]: ({ ...props }) => <Mobx {...props} />,
  ["mui"]: ({ ...props }) => <Mui {...props} />,
  ["nextui"]: ({ ...props }) => <Nextui {...props} />,
  ["nginx"]: ({ ...props }) => <Nginx {...props} />,
  ["pnpm"]: ({ ...props }) => <Pnpm {...props} />,
  ["react"]: ({ ...props }) => <React {...props} />,
  ["reactquery"]: ({ ...props }) => <Reactquery {...props} />,
  ["redux"]: ({ ...props }) => <Redux {...props} />,
  ["reporting"]: ({ ...props }) => <Reporting {...props} />,
  ["socket"]: ({ ...props }) => <Socket {...props} />,
  ["tailwind"]: ({ ...props }) => <Tailwind {...props} />,
  ["telegram"]: ({ ...props }) => <Telegram {...props} />,
  ["ts"]: ({ ...props }) => <Ts {...props} />,
  ["vite"]: ({ ...props }) => <Vite {...props} />,
};
